import { StyleSheet } from 'react-native';

export const familyStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FAF8',
  },
  content: {
    gap: 20,
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  eyebrow: {
    color: '#527469',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#10251F',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 36,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#10251F',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  familyStrip: {
    gap: 12,
    paddingRight: 20,
  },
  familyCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    minWidth: 150,
    padding: 14,
  },
  familyCardActive: {
    backgroundColor: '#10251F',
    borderColor: '#10251F',
  },
  familyName: {
    color: '#243A33',
    fontSize: 16,
    fontWeight: '800',
  },
  familyNameActive: {
    color: '#FFFFFF',
  },
  familyMeta: {
    color: '#66736E',
    fontSize: 13,
  },
  familyMetaActive: {
    color: '#C9D8D1',
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 18,
  },
  summaryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryLabel: {
    color: '#66736E',
    fontSize: 13,
    fontWeight: '700',
  },
  summaryTitle: {
    color: '#10251F',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: '#F0F5F2',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  iconButtonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  dangerIconButton: {
    backgroundColor: '#FCEEEE',
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#10251F',
    fontSize: 18,
    fontWeight: '800',
  },
  sectionActionButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  sectionAction: {
    color: '#157348',
    fontSize: 14,
    fontWeight: '800',
  },
  listCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
  },
  memberRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
  },
  budgetRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
  },
  budgetIcon: {
    alignItems: 'center',
    backgroundColor: '#E5F5EC',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#D9F2E4',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  avatarText: {
    color: '#0E2A21',
    fontSize: 14,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  memberCopy: {
    flex: 1,
  },
  memberName: {
    color: '#243A33',
    fontSize: 15,
    fontWeight: '800',
  },
  memberEmail: {
    color: '#66736E',
    fontSize: 13,
    marginTop: 2,
  },
  removeButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  modalOverlay: {
    backgroundColor: 'rgba(16, 37, 31, 0.28)',
    flex: 1,
  },
  modalKeyboardView: {
    flex: 1,
  },
  modalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 18,
    padding: 20,
  },
  modalHandle: {
    alignSelf: 'center',
    backgroundColor: '#DAE5DF',
    borderRadius: 999,
    height: 4,
    width: 42,
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalTitle: {
    color: '#10251F',
    fontSize: 22,
    fontWeight: '800',
  },
  fieldGroup: {
    gap: 8,
  },
  label: {
    color: '#243A33',
    fontSize: 14,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    color: '#142720',
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 15,
  },
  inputError: {
    borderColor: '#C64747',
  },
  errorText: {
    color: '#B73E3E',
    fontSize: 13,
    lineHeight: 18,
  },
  selectList: {
    gap: 10,
  },
  selectButton: {
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectButtonActive: {
    backgroundColor: '#10251F',
    borderColor: '#10251F',
  },
  selectButtonCopy: {
    flex: 1,
  },
  selectButtonText: {
    color: '#243A33',
    fontSize: 15,
    fontWeight: '800',
  },
  selectButtonTextActive: {
    color: '#FFFFFF',
  },
  selectButtonMeta: {
    color: '#66736E',
    fontSize: 12,
    marginTop: 2,
  },
  selectButtonMetaActive: {
    color: '#C9D8D1',
  },
  checkboxIcon: {
    alignItems: 'center',
    borderColor: '#B7C7BF',
    borderRadius: 6,
    borderWidth: 1,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  checkboxIconActive: {
    backgroundColor: '#157348',
    borderColor: '#157348',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#10251F',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 56,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 34,
  },
  emptyTitle: {
    color: '#243A33',
    fontSize: 16,
    fontWeight: '800',
  },
  emptyText: {
    color: '#66736E',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  confirmOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 37, 31, 0.32)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  confirmCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 12,
    padding: 20,
    width: '100%',
  },
  confirmIcon: {
    alignItems: 'center',
    backgroundColor: '#FCEEEE',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  confirmTitle: {
    color: '#10251F',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
    textAlign: 'center',
  },
  confirmText: {
    color: '#66736E',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  confirmActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
    width: '100%',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 50,
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: '#40534B',
    fontSize: 15,
    fontWeight: '800',
  },
  confirmDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#B73E3E',
    borderRadius: 8,
    flex: 1,
    minHeight: 50,
    justifyContent: 'center',
  },
  confirmDeleteButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
});
