import { StyleSheet } from 'react-native';

export const budgetStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FAF8',
  },
  content: {
    gap: 20,
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  formKeyboardView: {
    flex: 1,
  },
  formScreenContent: {
    gap: 20,
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  formHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  formHeaderCopy: {
    flex: 1,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  eyebrow: {
    color: '#527469',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#10251F',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 36,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#10251F',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  budgetList: {
    gap: 12,
    paddingRight: 20,
  },
  budgetCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    minWidth: 154,
    padding: 14,
  },
  budgetCardActive: {
    backgroundColor: '#10251F',
    borderColor: '#10251F',
  },
  budgetName: {
    color: '#40534B',
    fontSize: 14,
    fontWeight: '800',
  },
  budgetNameActive: {
    color: '#FFFFFF',
  },
  budgetBalance: {
    color: '#10251F',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  budgetBalanceActive: {
    color: '#FFFFFF',
  },
  budgetMeta: {
    color: '#66736E',
    fontSize: 13,
  },
  budgetMetaActive: {
    color: '#C9D8D1',
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 16,
    padding: 18,
    shadowColor: '#244035',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
  },
  summaryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionLabel: {
    color: '#66736E',
    fontSize: 13,
    fontWeight: '700',
  },
  activeTitle: {
    color: '#10251F',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0,
  },
  deleteButton: {
    alignItems: 'center',
    backgroundColor: '#FCEEEE',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  disabledButton: {
    opacity: 0.35,
  },
  amountRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  amountLabel: {
    color: '#66736E',
    fontSize: 13,
  },
  amountValue: {
    color: '#10251F',
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 40,
  },
  percentBadge: {
    backgroundColor: '#E6F6EE',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  percentText: {
    color: '#157348',
    fontSize: 13,
    fontWeight: '800',
  },
  progressTrack: {
    backgroundColor: '#DBE4DF',
    borderRadius: 999,
    height: 9,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: '#1D8E62',
    borderRadius: 999,
    height: '100%',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  statBox: {
    backgroundColor: '#F7FAF8',
    borderRadius: 8,
    flex: 1,
    gap: 4,
    padding: 12,
  },
  statLabel: {
    color: '#66736E',
    fontSize: 12,
  },
  statValue: {
    color: '#243A33',
    fontSize: 15,
    fontWeight: '800',
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#10251F',
    fontSize: 18,
    fontWeight: '800',
  },
  sectionAction: {
    color: '#157348',
    fontSize: 14,
    fontWeight: '800',
  },
  sectionActionButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  categoryList: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
  },
  categoryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
  },
  categoryIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  categoryCopy: {
    flex: 1,
  },
  categoryName: {
    color: '#243A33',
    fontSize: 15,
    fontWeight: '800',
  },
  categoryMeta: {
    color: '#66736E',
    fontSize: 13,
    marginTop: 2,
  },
  categoryAmount: {
    color: '#10251F',
    fontSize: 15,
    fontWeight: '800',
  },
  categoryEditButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 34,
  },
  emptyTitle: {
    color: '#243A33',
    fontSize: 16,
    fontWeight: '800',
  },
  emptyText: {
    color: '#66736E',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyButton: {
    backgroundColor: '#10251F',
    borderRadius: 8,
    marginTop: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  modalOverlay: {
    backgroundColor: 'rgba(16, 37, 31, 0.28)',
    flex: 1,
  },
  modalKeyboardView: {
    flex: 1,
  },
  modalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 18,
    padding: 20,
    shadowColor: '#10251F',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.18,
    shadowRadius: 28,
  },
  modalHandle: {
    alignSelf: 'center',
    backgroundColor: '#DAE5DF',
    borderRadius: 999,
    height: 4,
    width: 42,
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalTitle: {
    color: '#10251F',
    fontSize: 22,
    fontWeight: '800',
  },
  fieldGroup: {
    gap: 8,
  },
  label: {
    color: '#243A33',
    fontSize: 14,
    fontWeight: '700',
  },
  helperText: {
    color: '#66736E',
    fontSize: 13,
    lineHeight: 19,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    color: '#142720',
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 15,
  },
  inputError: {
    borderColor: '#C64747',
  },
  errorText: {
    color: '#B73E3E',
    fontSize: 13,
    lineHeight: 18,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#10251F',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 56,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  formActions: {
    gap: 12,
  },
  destructiveButton: {
    alignItems: 'center',
    backgroundColor: '#FCEEEE',
    borderColor: '#F2C9C9',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 54,
  },
  destructiveButtonText: {
    color: '#B73E3E',
    fontSize: 16,
    fontWeight: '800',
  },
  confirmOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 37, 31, 0.32)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  confirmCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 12,
    padding: 20,
    width: '100%',
  },
  confirmIcon: {
    alignItems: 'center',
    backgroundColor: '#FCEEEE',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  confirmTitle: {
    color: '#10251F',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
    textAlign: 'center',
  },
  confirmText: {
    color: '#66736E',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  confirmActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
    width: '100%',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 50,
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: '#40534B',
    fontSize: 15,
    fontWeight: '800',
  },
  confirmDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#B73E3E',
    borderRadius: 8,
    flex: 1,
    minHeight: 50,
    justifyContent: 'center',
  },
  confirmDeleteButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  presetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  presetButton: {
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  presetButtonActive: {
    backgroundColor: '#10251F',
    borderColor: '#10251F',
  },
  presetButtonText: {
    color: '#40534B',
    fontSize: 14,
    fontWeight: '800',
  },
  presetButtonTextActive: {
    color: '#FFFFFF',
  },
});
