import type { Transaction } from './types';

export const currentUserId = 'user-demo-1';

export const initialTransactions: Transaction[] = [
  {
    id: 'transaction-food-1',
    amount: 184,
    description: 'Zakupy spożywcze',
    transactionDate: '2026-05-14',
    createdAt: '2026-05-14T17:20:00.000Z',
    budgetId: 'home',
    userId: currentUserId,
    categoryId: 'food',
    currency: 'PLN',
  },
  {
    id: 'transaction-bills-1',
    amount: 320,
    description: 'Prąd i gaz',
    transactionDate: '2026-05-10',
    createdAt: '2026-05-10T09:30:00.000Z',
    budgetId: 'home',
    userId: currentUserId,
    categoryId: 'bills',
    currency: 'PLN',
  },
  {
    id: 'transaction-travel-1',
    amount: 120,
    description: 'Bilety kolejowe',
    transactionDate: '2026-05-08',
    createdAt: '2026-05-08T12:10:00.000Z',
    budgetId: 'holidays',
    userId: currentUserId,
    categoryId: 'travel',
    currency: 'PLN',
  },
  {
    id: 'transaction-salary-1',
    amount: 5800,
    description: 'Wynagrodzenie',
    transactionDate: '2026-05-01',
    createdAt: '2026-05-01T08:00:00.000Z',
    budgetId: 'home',
    userId: currentUserId,
    categoryId: 'salary',
    currency: 'PLN',
  },
  {
    id: 'transaction-food-previous',
    amount: 96,
    description: 'Piekarnia i warzywa',
    transactionDate: '2026-04-26',
    createdAt: '2026-04-26T13:40:00.000Z',
    budgetId: 'home',
    userId: currentUserId,
    categoryId: 'food',
    currency: 'PLN',
  },
  {
    id: 'transaction-fun-previous',
    amount: 75,
    description: 'Kino',
    transactionDate: '2026-04-12',
    createdAt: '2026-04-12T19:15:00.000Z',
    budgetId: 'home',
    userId: currentUserId,
    categoryId: 'fun',
    currency: 'PLN',
  },
];
