import { StyleSheet } from 'react-native';

export const transactionStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FAF8',
  },
  content: {
    gap: 20,
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  eyebrow: {
    color: '#527469',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#10251F',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 36,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#10251F',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 18,
  },
  summaryLabel: {
    color: '#66736E',
    fontSize: 13,
    fontWeight: '700',
  },
  summaryValue: {
    color: '#10251F',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 0,
  },
  listCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
  },
  transactionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 76,
  },
  transactionIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  transactionCopy: {
    flex: 1,
  },
  transactionTitle: {
    color: '#243A33',
    fontSize: 15,
    fontWeight: '800',
  },
  transactionMeta: {
    color: '#66736E',
    fontSize: 13,
    marginTop: 2,
  },
  transactionAmount: {
    color: '#B73E3E',
    fontSize: 15,
    fontWeight: '800',
  },
  positiveAmount: {
    color: '#157348',
  },
  editButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 34,
  },
  emptyTitle: {
    color: '#243A33',
    fontSize: 16,
    fontWeight: '800',
  },
  emptyText: {
    color: '#66736E',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyButton: {
    backgroundColor: '#10251F',
    borderRadius: 8,
    marginTop: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  formKeyboardView: {
    flex: 1,
  },
  formContent: {
    gap: 20,
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  formHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  formHeaderCopy: {
    flex: 1,
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 18,
    padding: 18,
  },
  fieldGroup: {
    gap: 8,
  },
  label: {
    color: '#243A33',
    fontSize: 14,
    fontWeight: '700',
  },
  helperText: {
    color: '#66736E',
    fontSize: 13,
    lineHeight: 19,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    color: '#142720',
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 15,
  },
  inputError: {
    borderColor: '#C64747',
  },
  dateButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 56,
    paddingHorizontal: 15,
  },
  dateButtonText: {
    color: '#142720',
    fontSize: 16,
    fontWeight: '700',
  },
  errorText: {
    color: '#B73E3E',
    fontSize: 13,
    lineHeight: 18,
  },
  selectList: {
    gap: 10,
  },
  selectButton: {
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectButtonActive: {
    backgroundColor: '#10251F',
    borderColor: '#10251F',
  },
  selectButtonCopy: {
    flex: 1,
  },
  selectButtonText: {
    color: '#243A33',
    fontSize: 15,
    fontWeight: '800',
  },
  selectButtonTextActive: {
    color: '#FFFFFF',
  },
  selectButtonMeta: {
    color: '#66736E',
    fontSize: 12,
    marginTop: 2,
  },
  selectButtonMetaActive: {
    color: '#C9D8D1',
  },
  compactGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  compactOption: {
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  compactOptionActive: {
    backgroundColor: '#10251F',
    borderColor: '#10251F',
  },
  compactOptionText: {
    color: '#40534B',
    fontSize: 13,
    fontWeight: '800',
  },
  compactOptionTextActive: {
    color: '#FFFFFF',
  },
  formActions: {
    gap: 12,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#10251F',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 56,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  destructiveButton: {
    alignItems: 'center',
    backgroundColor: '#FCEEEE',
    borderColor: '#F2C9C9',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 54,
  },
  destructiveButtonText: {
    color: '#B73E3E',
    fontSize: 16,
    fontWeight: '800',
  },
  confirmOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 37, 31, 0.32)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  confirmCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 12,
    padding: 20,
    width: '100%',
  },
  datePickerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 16,
    padding: 20,
    width: '100%',
  },
  datePickerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  confirmIcon: {
    alignItems: 'center',
    backgroundColor: '#FCEEEE',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  confirmTitle: {
    color: '#10251F',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
    textAlign: 'center',
  },
  confirmText: {
    color: '#66736E',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  confirmActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
    width: '100%',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderColor: '#DAE5DF',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 50,
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: '#40534B',
    fontSize: 15,
    fontWeight: '800',
  },
  confirmDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#B73E3E',
    borderRadius: 8,
    flex: 1,
    minHeight: 50,
    justifyContent: 'center',
  },
  confirmDeleteButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
});
